### ISSUE TITLE
Citer is unable to find an existing file.

### ISSUE THREAD

**Issue by wolass** [mangecoeur/Citer#15]
I am trying to use Citer on a Ubuntu with Sublime 3 beta. 
My console shows the following:

    reloading plugin Citer.citer
    plugins loaded 
    Traceback (most recent call last):
    File "/opt/sublime_text/sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
    File "/home/wojtek/.config/sublime-text-3/Packages/Citer/citer.py", line 69, in plugin_loaded
    refresh_caches()
    File "/home/wojtek/.config/sublime-text-3/Packages/Citer/citer.py", line 93, in refresh_caches
    last_modified_time = os.path.getmtime(BIBFILE_PATH)
    File "./genericpath.py", line 54, in getmtime
    FileNotFoundError: [Errno 2] No such file or directory: '/home/wojtek/o.bib ' 

but the command 

    nano /home/wojtek/o.bib

Opens the file in the nano editor.... 

Any ideas?

**Comment by mangecoeur** [comment]
My first instinct is that `'/home/wojtek/o.bib ' `  has an extra space at the end. Not sure if this is causing the issue. In any case, I am pushing a minor update that strips whitespace from start/end of file paths

**Comment by wolass** [comment]
You were right this was the issue!
Thanks for the fast reply and sorry for not seeing extra spaces :)
