### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by rtwld** [mangecoeur/Citer#27]
I'm using Citer version 0.6.2 and ST3 (3083). Just installed, and I've run into the following problem:

`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/Users/dan/Library/Application Support/Sublime Text 3/Packages/Citer/citer.py", line 235, in run
    ctk = citekeys_menu()
  File "/Users/dan/Library/Application Support/Sublime Text 3/Packages/Citer/citer.py", line 173, in citekeys_menu
    refresh_caches()
  File "/Users/dan/Library/Application Support/Sublime Text 3/Packages/Citer/citer.py", line 108, in refresh_caches
    if bibfile_modifed(BIBFILE_PATH):
  File "/Users/dan/Library/Application Support/Sublime Text 3/Packages/Citer/citer.py", line 77, in bibfile_modifed
    bib_path = bib_path.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
`

Any help?

**Comment by mangecoeur** [comment]
For some reason the bib_path is None . Have you set the path to your bibliography file?

**Comment by rtwld** [comment]
I did: 

> {
> …
> "bibtex_file_path": "/Users/[stripped]/Dropbox/bibliothek/bibdesk/mainbib.bib",
> …
> }
>

**Comment by mangecoeur** [comment]
hmm can't see any obvious cause... try restarting ST :/ am tagging a new release with some extra features, it will take some time to filter through the package system

**Comment by rtwld** [comment]
My bad. It seems I put the the required configuration in `Preferences.sublime-settings`. Moving the configuration options to `Citer.sublime-settings` solves the problem. 

Newbie mistake, sorry.

**Comment by rtwld** [comment]
mangecoeur/Citer#28

**Comment by rtwld** [comment]
#28

**Comment by rtwld** [comment]
I've issued a pull request: https://github.com/mangecoeur/Citer/pull/28
